version: '3'
services:
  user-service:
    build: ./user
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  post-service:
    build: ./post
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - user-service

  notification-service:
    build: ./notification
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    depends_on:
      - user-service
      - post-service

networks:
  microservices-network:
    driver: bridge
